import Link from "next/link"
import { Button } from "@/components/ui/button"
import { ArrowRight, BookOpen, GraduationCap, QrCode } from "lucide-react"

export default function LandingPage() {
  return (
    <div className="flex flex-col items-center justify-center min-h-[80vh] px-4 text-center space-y-8">
      
      {/* Hero Section */}
      <div className="space-y-4 max-w-2xl">
        <div className="inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 border-transparent bg-blue-100 text-blue-800 hover:bg-blue-200">
          New: QR Attendance Tracking
        </div>
        <h1 className="text-4xl font-extrabold tracking-tight lg:text-6xl text-slate-900">
          Attend<span className="text-blue-600">Sync</span>
        </h1>
        <p className="text-xl text-slate-500 mx-auto max-w-[600px]">
          The modern, seamless way to track university attendance. 
          No more paper sheets—just scan and go.
        </p>
      </div>

      {/* Action Buttons */}
      <div className="flex flex-col sm:flex-row gap-4 w-full max-w-md justify-center">
        <Button asChild size="lg" className="w-full sm:w-auto bg-blue-600 hover:bg-blue-700 h-14 text-lg">
          <Link href="/auth/login">
            Get Started <ArrowRight className="ml-2 h-5 w-5" />
          </Link>
        </Button>
        <Button asChild variant="outline" size="lg" className="w-full sm:w-auto h-14 text-lg">
          <Link href="/about">
            Learn More
          </Link>
        </Button>
      </div>

      {/* Feature Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mt-12 text-left max-w-4xl w-full">
        <div className="bg-slate-50 p-6 rounded-2xl border border-slate-100">
          <QrCode className="h-10 w-10 text-blue-600 mb-4" />
          <h3 className="font-bold text-lg mb-2">Instant Scan</h3>
          <p className="text-slate-500 text-sm">Students scan a dynamic QR code generated by the teacher to mark attendance instantly.</p>
        </div>
        <div className="bg-slate-50 p-6 rounded-2xl border border-slate-100">
          <BookOpen className="h-10 w-10 text-blue-600 mb-4" />
          <h3 className="font-bold text-lg mb-2">Real-time Records</h3>
          <p className="text-slate-500 text-sm">Teachers can see who is present in real-time and export reports anytime.</p>
        </div>
        <div className="bg-slate-50 p-6 rounded-2xl border border-slate-100">
          <GraduationCap className="h-10 w-10 text-blue-600 mb-4" />
          <h3 className="font-bold text-lg mb-2">Student Analytics</h3>
          <p className="text-slate-500 text-sm">Students can track their own attendance history and stay accountable.</p>
        </div>
      </div>

    </div>
  )
}